# Generated by Django 5.0.4 on 2024-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('resource_count', models.IntegerField()),
            ],
        ),
    ]
